[package]
name = "liushu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
redb = "0.13.0"

liushu-core = { path = "liushu-core" }

[workspace]
members = [
    "liushu-core",
    "liushu-ls",
]
