[package]
name = "liushu-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]
name = "liushu_ffi"

[dependencies]
uniffi = { version = "0.23.0" }
liushu-core = { path = "../liushu-core" }

[build-dependencies]
uniffi = { version = "0.23.0", features = [ "build" ] }
