name: "Test & Lint & Format"
on:
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test-workspace:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check

      - name: rust test
        run: nix develop --command cargo test --workspace

      - name: rust lint
        run: nix develop --command cargo clippy -- -D warnings

      - name: rust format
        run: nix develop --command cargo fmt --all -- --check
